/**
 * build-sdk.mjs
 *
 * Validates SDK plugins (those that export tools as a function) and
 * generates TypeScript declaration files (.d.ts) for the plugin interface.
 *
 * Used by CI / Build (SDK with DTS) workflow.
 */

import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, join } from "node:path";
import { pathToFileURL } from "node:url";

const PLUGINS_DIR = resolve("plugins");
const DIST_DIR = resolve("dist");

// Minimal mock SDK for initialization
const MOCK_SDK = {
  ton: {
    getAddress: () => null,
    getPublicKey: () => null,
    getWalletVersion: () => "v5r1",
    getBalance: async () => null,
    getPrice: async () => null,
    sendTON: async () => { throw new Error("mock"); },
    getTransactions: async () => [],
    verifyPayment: async () => ({ verified: false }),
    getJettonBalances: async () => [],
    getJettonInfo: async () => null,
    sendJetton: async () => { throw new Error("mock"); },
    createJettonTransfer: async () => { throw new Error("mock"); },
    getJettonWalletAddress: async () => null,
    getNftItems: async () => [],
    getNftInfo: async () => null,
    toNano: (v) => BigInt(Math.round(parseFloat(v) * 1e9)),
    fromNano: (v) => String(Number(v) / 1e9),
    validateAddress: () => false,
    getJettonPrice: async () => null,
    getJettonHolders: async () => [],
    getJettonHistory: async () => null,
    dex: {
      quote: async () => { throw new Error("mock"); },
      quoteSTONfi: async () => null,
      quoteDeDust: async () => null,
      swap: async () => { throw new Error("mock"); },
      swapSTONfi: async () => { throw new Error("mock"); },
      swapDeDust: async () => { throw new Error("mock"); },
    },
    dns: {
      check: async () => ({ available: false }),
      resolve: async () => null,
      getAuctions: async () => [],
      startAuction: async () => { throw new Error("mock"); },
      bid: async () => { throw new Error("mock"); },
      link: async () => { throw new Error("mock"); },
      unlink: async () => { throw new Error("mock"); },
      setSiteRecord: async () => { throw new Error("mock"); },
    },
  },
  telegram: {
    sendMessage: async () => 0,
    editMessage: async () => 0,
    deleteMessage: async () => {},
    getMessages: async () => [],
    getMe: async () => null,
    isAvailable: () => false,
    getRawClient: () => null,
  },
  bot: {
    onInlineQuery: () => {},
    onCallback: () => {},
    answerInline: async () => {},
    answerCallback: async () => {},
  },
  db: null,
  log: {
    info: () => {},
    warn: () => {},
    error: () => {},
    debug: () => {},
  },
  pluginConfig: {},
  secrets: { get: async () => null },
};

/**
 * Generate a TypeScript declaration file for a plugin's tools.
 */
function generateDts(pluginName, toolList) {
  const toolInterfaces = toolList.map((tool) => {
    const name = tool.name ?? "unknown";
    const description = (tool.description ?? "").replace(/\*\//g, "* /");
    return `  /** ${description} */\n  readonly ${JSON.stringify(name)}: ToolDefinition;`;
  }).join("\n");

  return `// Auto-generated by build-sdk.mjs — do not edit manually
// Plugin: ${pluginName}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters?: Record<string, unknown>;
  execute: (params: Record<string, unknown>, context: unknown) => Promise<ToolResult>;
  scope?: "always" | "dm-only" | "group-only" | "admin-only";
  category?: "data-bearing" | "action";
}

export interface ToolResult {
  success: boolean;
  data?: Record<string, unknown>;
  error?: string;
}

export interface Plugin {
  tools: ToolDefinition[] | ((sdk: unknown) => ToolDefinition[]);
}

export declare const tools: ToolDefinition[] | ((sdk: unknown) => ToolDefinition[]);

export declare const toolMap: {
${toolInterfaces}
};
`;
}

let errors = 0;
let sdkPlugins = 0;

const entries = await readdir(PLUGINS_DIR, { withFileTypes: true });
const pluginDirs = entries
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

await mkdir(DIST_DIR, { recursive: true });

console.log(`\nBuilding SDK plugins from ${pluginDirs.length} total plugins...\n`);

for (const name of pluginDirs) {
  const dir = join(PLUGINS_DIR, name);
  const indexPath = join(dir, "index.js");

  if (!existsSync(indexPath)) continue;

  let mod;
  try {
    mod = await import(pathToFileURL(indexPath).href);
  } catch (e) {
    // If the import fails, skip this plugin (already reported in build-runtime)
    console.log(`  [SKIP] ${name}: import failed (missing deps?)`);
    continue;
  }

  if (!mod.tools) continue;

  // Only process SDK plugins (tools as function)
  if (typeof mod.tools !== "function") {
    console.log(`  [SKIP] ${name}: not an SDK plugin`);
    continue;
  }

  sdkPlugins++;

  let toolList;
  try {
    toolList = mod.tools(MOCK_SDK);
  } catch (e) {
    console.error(`  [ERROR] ${name}: tools(sdk) threw: ${e.message}`);
    errors++;
    continue;
  }

  if (!Array.isArray(toolList)) {
    console.error(`  [ERROR] ${name}: tools(sdk) did not return an array`);
    errors++;
    continue;
  }

  // Generate .d.ts file
  const dtsContent = generateDts(name, toolList);
  const dtsPath = join(DIST_DIR, `${name}.d.ts`);
  await writeFile(dtsPath, dtsContent, "utf8");

  console.log(`  [OK]    ${name}: ${toolList.length} tool(s) → dist/${name}.d.ts`);
}

console.log(`\nResult: ${sdkPlugins} SDK plugin(s) processed, ${errors} error(s)\n`);

if (errors > 0) {
  process.exit(1);
}
